apiVersion: v1
kind: Service
metadata:
  name: gbg-backend
  labels:
    app: gbg-backend
spec:
  ports:
    - port: 8001
      targetPort: 8001
      name: http
  selector:
    app: gbg-backend
  type: ClusterIP
